import { getDb } from "@/lib/db";

/**
 * Cross-conversation memory for the Yara agent, keyed by WhatsApp user ID.
 *
 * Write path: the ElevenLabs post-call webhook stores each conversation's
 * summary (generated by ElevenLabs) plus any collected name/email.
 * Read path: injected at conversation start (initiation webhook) or fetched
 * by the recall_customer tool, so Yara recognizes returning clients.
 */

export type MemoryEntry = {
  at: string;
  conversation_id: string;
  summary: string;
};

export type CustomerMemory = {
  whatsappUserId: string;
  customerName: string | null;
  email: string | null;
  summaries: MemoryEntry[];
  lastSeenAt: string;
};

const KEEP_SUMMARIES = 5;

let ensured: Promise<unknown> | null = null;
function ensureTable() {
  if (!ensured) {
    const sql = getDb();
    ensured = sql`
      CREATE TABLE IF NOT EXISTS customer_memory (
        whatsapp_user_id TEXT PRIMARY KEY,
        customer_name TEXT,
        email TEXT,
        summaries JSONB NOT NULL DEFAULT '[]'::jsonb,
        last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `;
  }
  return ensured;
}

/* eslint-disable @typescript-eslint/no-explicit-any */
function rowToMemory(row: any): CustomerMemory {
  return {
    whatsappUserId: row.whatsapp_user_id,
    customerName: row.customer_name,
    email: row.email,
    summaries: row.summaries || [],
    lastSeenAt: row.last_seen_at,
  };
}

export async function getCustomerMemory(
  whatsappUserId: string
): Promise<CustomerMemory | null> {
  await ensureTable();
  const sql = getDb();
  const rows = await sql`
    SELECT * FROM customer_memory WHERE whatsapp_user_id = ${whatsappUserId} LIMIT 1
  `;
  return rows.length ? rowToMemory(rows[0]) : null;
}

export async function upsertCustomerMemory(input: {
  whatsappUserId: string;
  customerName?: string | null;
  email?: string | null;
  conversationId: string;
  summary?: string | null;
}): Promise<void> {
  await ensureTable();
  const sql = getDb();

  const entry: MemoryEntry[] = input.summary
    ? [
        {
          at: new Date().toISOString(),
          conversation_id: input.conversationId,
          summary: input.summary.slice(0, 1500),
        },
      ]
    : [];

  await sql`
    INSERT INTO customer_memory (whatsapp_user_id, customer_name, email, summaries, last_seen_at)
    VALUES (
      ${input.whatsappUserId},
      ${input.customerName ?? null},
      ${input.email ?? null},
      ${JSON.stringify(entry)}::jsonb,
      now()
    )
    ON CONFLICT (whatsapp_user_id) DO UPDATE SET
      customer_name = COALESCE(EXCLUDED.customer_name, customer_memory.customer_name),
      email = COALESCE(EXCLUDED.email, customer_memory.email),
      summaries = (
        SELECT COALESCE(jsonb_agg(e ORDER BY (e->>'at') DESC), '[]'::jsonb)
        FROM (
          SELECT e
          FROM jsonb_array_elements(customer_memory.summaries || EXCLUDED.summaries) e
          ORDER BY (e->>'at') DESC
          LIMIT ${KEEP_SUMMARIES}
        ) trimmed
      ),
      last_seen_at = now()
  `;
}

/**
 * Compact, prompt-injectable description of what we know about the client.
 * Empty string when there is nothing — the prompt treats that as a new client.
 */
export function formatCustomerContext(memory: CustomerMemory | null): string {
  if (!memory || memory.summaries.length === 0) return "";

  const lastSeen = new Date(memory.lastSeenAt).toDateString();
  const lines = [
    `Returning client${memory.customerName ? `: ${memory.customerName}` : ""}.`,
    memory.email ? `Email on file: ${memory.email}.` : "",
    `Last conversation: ${lastSeen}.`,
    "Previous conversations (newest first):",
    ...memory.summaries.map(
      (s) => `- [${new Date(s.at).toDateString()}] ${s.summary}`
    ),
  ].filter(Boolean);

  return lines.join("\n").slice(0, 2500);
}
